In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Machine Learning/Wine.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [5]:
dataset

Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0      14.23        1.71  2.43          15.6        127           2.80   
1      13.20        1.78  2.14          11.2        100           2.65   
2      13.16        2.36  2.67          18.6        101           2.80   
3      14.37        1.95  2.50          16.8        113           3.85   
4      13.24        2.59  2.87          21.0        118           2.80   
..       ...         ...   ...           ...        ...            ...   
173    13.71        5.65  2.45          20.5         95           1.68   
174    13.40        3.91  2.48          23.0        102           1.80   
175    13.27        4.28  2.26          20.0        120           1.59   
176    13.17        2.59  2.37          20.0        120           1.65   
177    14.13        4.10  2.74          24.5         96           2.05   

     Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity   Hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     OD280  Proline  Customer_Segment  
0     3.92     1065                 1  
1     3.40     1050                 1  
2     3.17     1185                 1  
3     3.45     1480                 1  
4     2.93      735                 1  
..     ...      ...               ...  
173   1.74      740                 3  
174   1.56      750                 3  
175   1.56      835                 3  
176   1.62      840                 3  
177   1.60      560                 3  

[178 rows x 14 columns]

In [3]:
X

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [4]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3])

# PCA

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [14]:
X_train

array([[-9.95027381e-01, -6.76569483e-01],
       [-8.25758990e-01,  9.95889837e-01],
       [ 5.01565410e-01,  1.40164803e+00],
       [-1.16719551e+00, -1.04881992e+00],
       [ 8.48039433e-01,  1.52437389e-01],
       [ 1.17954326e+00, -8.68713059e-01],
       [ 3.98622020e-01,  1.42369691e+00],
       [-1.91066158e-01,  1.48551896e+00],
       [-1.39275944e-01,  1.43657551e+00],
       [ 9.77664638e-01, -6.94455126e-01],
       [-1.36151921e+00, -1.55962275e-01],
       [ 8.95945619e-01,  7.91347336e-01],
       [-9.87233211e-01, -6.15853968e-01],
       [ 1.01371263e+00, -1.51133703e+00],
       [-1.05117584e+00, -1.29858750e-01],
       [-1.37438543e+00, -1.76143560e-01],
       [ 1.20308446e+00, -5.47922549e-01],
       [-4.98781924e-01, -2.23321997e+00],
       [ 1.19913403e+00, -1.87319944e-03],
       [ 9.04572692e-02,  1.44625542e+00],
       [-1.22134823e+00, -1.63307941e+00],
       [-1.16344596e+00, -2.85665003e-01],
       [ 8.10220559e-01,  5.32319846e-01],
       [-1.

In [15]:
X_test

array([[ 1.00781752e+00, -6.49004145e-01],
       [-1.15836893e+00, -1.15883097e+00],
       [ 1.00095867e+00,  1.14366310e+00],
       [ 1.14849234e+00, -8.76535386e-01],
       [-1.58919458e-01,  3.31536351e-01],
       [ 6.58409095e-01, -1.82790280e-01],
       [ 9.67661201e-01, -1.02831059e+00],
       [-1.39764001e+00, -4.23382961e-01],
       [-1.07518491e-01,  1.36811474e+00],
       [-5.53632355e-01,  1.33905467e+00],
       [-1.00791575e+00, -1.64984642e-01],
       [-1.91694340e+00, -3.38545480e-01],
       [ 1.42055394e+00, -1.42850641e+00],
       [ 1.09546777e+00,  8.17056763e-01],
       [-9.86891423e-01, -1.23255546e+00],
       [ 4.23168892e-01,  2.11819592e+00],
       [ 8.99426328e-01, -1.04200309e+00],
       [ 1.65048904e+00, -1.69168747e+00],
       [-7.85420496e-01,  5.86808399e-01],
       [ 1.33903398e+00, -5.54868583e-01],
       [ 1.08192143e+00,  1.09274819e+00],
       [ 5.63395060e-01, -9.87708347e-02],
       [ 4.91043962e-01, -5.66176520e-01],
       [ 2.

In [17]:
from sklearn.decomposition import PCA
pca = PCA(n_components = 2)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

In [18]:
X_train

array([[-9.95027381e-01, -6.76569483e-01],
       [-8.25758990e-01,  9.95889837e-01],
       [ 5.01565410e-01,  1.40164803e+00],
       [-1.16719551e+00, -1.04881992e+00],
       [ 8.48039433e-01,  1.52437389e-01],
       [ 1.17954326e+00, -8.68713059e-01],
       [ 3.98622020e-01,  1.42369691e+00],
       [-1.91066158e-01,  1.48551896e+00],
       [-1.39275944e-01,  1.43657551e+00],
       [ 9.77664638e-01, -6.94455126e-01],
       [-1.36151921e+00, -1.55962275e-01],
       [ 8.95945619e-01,  7.91347336e-01],
       [-9.87233211e-01, -6.15853968e-01],
       [ 1.01371263e+00, -1.51133703e+00],
       [-1.05117584e+00, -1.29858750e-01],
       [-1.37438543e+00, -1.76143560e-01],
       [ 1.20308446e+00, -5.47922549e-01],
       [-4.98781924e-01, -2.23321997e+00],
       [ 1.19913403e+00, -1.87319944e-03],
       [ 9.04572692e-02,  1.44625542e+00],
       [-1.22134823e+00, -1.63307941e+00],
       [-1.16344596e+00, -2.85665003e-01],
       [ 8.10220559e-01,  5.32319846e-01],
       [-1.

In [19]:
X_test

array([[ 1.00781752e+00, -6.49004145e-01],
       [-1.15836893e+00, -1.15883097e+00],
       [ 1.00095867e+00,  1.14366310e+00],
       [ 1.14849234e+00, -8.76535386e-01],
       [-1.58919458e-01,  3.31536351e-01],
       [ 6.58409095e-01, -1.82790280e-01],
       [ 9.67661201e-01, -1.02831059e+00],
       [-1.39764001e+00, -4.23382961e-01],
       [-1.07518491e-01,  1.36811474e+00],
       [-5.53632355e-01,  1.33905467e+00],
       [-1.00791575e+00, -1.64984642e-01],
       [-1.91694340e+00, -3.38545480e-01],
       [ 1.42055394e+00, -1.42850641e+00],
       [ 1.09546777e+00,  8.17056763e-01],
       [-9.86891423e-01, -1.23255546e+00],
       [ 4.23168892e-01,  2.11819592e+00],
       [ 8.99426328e-01, -1.04200309e+00],
       [ 1.65048904e+00, -1.69168747e+00],
       [-7.85420496e-01,  5.86808399e-01],
       [ 1.33903398e+00, -5.54868583e-01],
       [ 1.08192143e+00,  1.09274819e+00],
       [ 5.63395060e-01, -9.87708347e-02],
       [ 4.91043962e-01, -5.66176520e-01],
       [ 2.

In [20]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[14  0  0]
 [ 1 15  0]
 [ 0  0  6]]


0.9722222222222222

# LDA


In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [22]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [24]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda = LDA(n_components = 2)
X_train = lda.fit_transform(X_train, y_train)
X_test = lda.transform(X_test)

In [25]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[14  0  0]
 [ 0 16  0]
 [ 0  0  6]]


1.0

# kernal pca


In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [27]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [28]:
from sklearn.decomposition import KernelPCA
kpca = KernelPCA(n_components = 2, kernel = 'rbf')
X_train = kpca.fit_transform(X_train)
X_test = kpca.transform(X_test)

In [29]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[14  0  0]
 [ 0 16  0]
 [ 0  0  6]]


1.0